language: c

os:
  - osx
  - linux

addons:
  apt:
    packages:
      - libc6:i386
      - libuuid1:i386
      - libkrb5-3:i386
      - libk5crypto3:i386
      - zlib1g:i386
      - libcomerr2:i386
      - libkrb5support0:i386
      - libkeyutils1:i386
      - libssl1.0.0:i386
      - libfreetype6:i386

install: 
  - wget -O - get.pharo.org/50+vm | bash
  - ./scripts/install-packages.sh

script:
  - ./pharo Pharo.image test --fail-on-failure "J2Inferer-*"
